#!/usr/bin/env python3
"""Generate Codex subagent TOML files from plugin SKILL.md sources.

SKILL.md is the single source of truth. Run this script after editing any
perspective skill to refresh `.codex/agents/*.toml`.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
SKILLS_ROOT = REPO_ROOT / "plugins" / "pr-review-toolkit" / "skills"
AGENTS_ROOT = REPO_ROOT / ".codex" / "agents"

PERSPECTIVE_SKILLS = [
    "code-reviewer",
    "silent-failure-hunter",
    "pr-test-analyzer",
    "comment-analyzer",
    "type-design-analyzer",
    "code-simplifier",
]

CATEGORY_BY_SKILL = {
    "code-reviewer": "correctness, security, maintainability",
    "silent-failure-hunter": "silent-failure",
    "pr-test-analyzer": "test-coverage",
    "comment-analyzer": "comments",
    "type-design-analyzer": "type-design",
    "code-simplifier": "simplicity",
}

SUBAGENT_ROLE = """\
あなたは PR レビュー用の専門 subagent です。親セッションから渡されたスコープ（base branch、対象ファイル、差分）に限定してレビューしてください。

## 役割
- レビューのみ。コードの自動修正は行わない
- sandbox bypass や承認スキップを前提にしない
- プロジェクトに `AGENTS.md` 等の規約があれば先に読む
- cosmetic 指摘は出さない。P3 はデフォルトで出さない
"""

DEFAULT_OUTPUT_SECTION = """\
## 出力（親セッションが統合するため、この形式を守る）
Finding がある場合のみ、以下の形式で返す。観点ごとの長文レポートは不要。

### P[0-3]: [短いタイトル]
- File: `path`
- Lines: N-M
- Category: {category}
- Problem:
- Impact:
- Suggested fix: （または Suggested test:）

Finding がなければ `No findings from {skill_name} perspective.` と1行で返す。
"""

COMMENT_ANALYZER_OUTPUT_SECTION = """\
## 出力（親セッションが統合するため、この形式を守る）
Finding がある場合、または Finding はないが未検証の外部出典など Notes を残す必要がある場合は、次の形式を使う。観点ごとの長文レポートは不要。

### P[0-3]: [短いタイトル]
- File: `path`
- Lines: N-M
- Category: comments
- Problem:
- Impact:
- Suggested fix:

Finding がなく Notes のみある場合:

## Notes

- 未検証: [項目]（確認不能な理由）

Finding と Notes の両方がある場合は Findings を先に、続けて Notes を返す。

Finding も Notes もない場合のみ `No findings from comment-analyzer perspective.` と1行で返す。
"""

OUTPUT_SECTION_BY_SKILL = {
    "comment-analyzer": COMMENT_ANALYZER_OUTPUT_SECTION,
}

SUBAGENT_PREAMBLE_SUFFIX = """\

---

以下がこの観点の詳細手順です:

"""


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate Codex subagent TOML files from SKILL.md.")
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit with status 1 if generated files would change.",
    )
    return parser.parse_args()


def parse_skill_md(path: Path) -> tuple[str, str, str]:
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---\n"):
        raise ValueError(f"{path}: missing YAML frontmatter")
    end = text.find("\n---", 4)
    if end == -1:
        raise ValueError(f"{path}: unclosed frontmatter")
    frontmatter = yaml.safe_load(text[4:end])
    if not isinstance(frontmatter, dict):
        raise ValueError(f"{path}: frontmatter must be an object")
    name = frontmatter.get("name")
    description = frontmatter.get("description")
    if not isinstance(name, str) or not name.strip():
        raise ValueError(f"{path}: frontmatter field `name` is required")
    if not isinstance(description, str) or not description.strip():
        raise ValueError(f"{path}: frontmatter field `description` is required")
    body = text[end + 4 :].lstrip("\n")
    return name.strip(), description.strip(), body


def render_toml(name: str, description: str, developer_instructions: str) -> str:
    header = (
        "# Generated by scripts/generate_subagents.py — do not edit by hand.\n"
        "# Source: plugins/pr-review-toolkit/skills/{name}/SKILL.md\n\n"
    ).format(name=name)
    return (
        header
        + f'name = "{escape_toml_string(name)}"\n'
        + f'description = "{escape_toml_string(description)}"\n'
        + 'developer_instructions = """\n'
        + developer_instructions.rstrip()
        + '\n"""\n'
    )


def escape_toml_string(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def generate_agent_toml(skill_name: str) -> str:
    skill_path = SKILLS_ROOT / skill_name / "SKILL.md"
    name, description, body = parse_skill_md(skill_path)
    if name != skill_name:
        raise ValueError(f"{skill_path}: frontmatter name `{name}` != directory `{skill_name}`")
    category = CATEGORY_BY_SKILL[skill_name]
    output_section = OUTPUT_SECTION_BY_SKILL.get(
        skill_name,
        DEFAULT_OUTPUT_SECTION.format(category=category, skill_name=skill_name),
    )
    preamble = SUBAGENT_ROLE + "\n" + output_section + SUBAGENT_PREAMBLE_SUFFIX
    return render_toml(name, description, preamble + body)


def write_config_toml() -> str:
    return """\
# Codex subagent settings for pr-review parallel mode.
# See README.md and plugins/pr-review-toolkit/skills/pr-review/SKILL.md.

[agents]
max_threads = 6
max_depth = 1
"""


def main() -> None:
    args = parse_args()
    errors: list[str] = []
    stale_files: list[str] = []

    config_path = REPO_ROOT / ".codex" / "config.toml"
    config_content = write_config_toml()
    if args.check:
        if not config_path.is_file() or config_path.read_text(encoding="utf-8") != config_content:
            stale_files.append(str(config_path.relative_to(REPO_ROOT)))
    else:
        config_path.parent.mkdir(parents=True, exist_ok=True)
        config_path.write_text(config_content, encoding="utf-8")

    AGENTS_ROOT.mkdir(parents=True, exist_ok=True)

    for skill_name in PERSPECTIVE_SKILLS:
        try:
            content = generate_agent_toml(skill_name)
        except (OSError, ValueError, yaml.YAMLError) as exc:
            errors.append(f"{skill_name}: {exc}")
            continue

        out_path = AGENTS_ROOT / f"{skill_name}.toml"
        if args.check:
            if not out_path.is_file() or out_path.read_text(encoding="utf-8") != content:
                stale_files.append(str(out_path.relative_to(REPO_ROOT)))
        else:
            out_path.write_text(content, encoding="utf-8")

    if errors:
        print("Subagent generation failed:", file=sys.stderr)
        for error in errors:
            print(f"- {error}", file=sys.stderr)
        raise SystemExit(1)

    if args.check and stale_files:
        print("Subagent TOML is out of date. Run: python3 scripts/generate_subagents.py")
        for path in stale_files:
            print(f"- {path}")
        raise SystemExit(1)

    if args.check:
        print("Subagent TOML is up to date.")
    else:
        print(f"Generated subagents in {AGENTS_ROOT.relative_to(REPO_ROOT)}/")


if __name__ == "__main__":
    main()
